#ifndef PROTOCOL_CONFIG_H
#define PROTOCOL_CONFIG_H

#define RAYZ_PROTOCOL_VERSION "1.0.0"

// Timing (ms)
#define BIT_DURATION_MS 3
#define SAMPLE_INTERVAL_MS 1
#define SAMPLES_PER_BIT 3
#define TRANSMISSION_PAUSE_MS 100
#define COMMUNICATION_TIMEOUT_MS 5000

// Message structure
#define MESSAGE_TOTAL_BITS 32
#define MESSAGE_DATA_BITS 32
#define MESSAGE_HASH_BITS 8

// Buffers
#define PHOTODIODE_BUFFER_SIZE MESSAGE_TOTAL_BITS
#define MAX_MESSAGE_SIZE 256

#define MESSAGE_DURATION_MS (BIT_DURATION_MS * MESSAGE_TOTAL_BITS)

// Hash
#define HASH_XOR_SEED 0b10101010
#define HASH_OFFSET 1

// Threshold weights
#define THRESHOLD_MIN_WEIGHT 0.98f
#define THRESHOLD_NEW_WEIGHT 0.02f
#define THRESHOLD_SMOOTH_OLD 0.7f
#define THRESHOLD_SMOOTH_NEW 0.3f

// BLE
#define BLE_RECONNECT_DELAY_MS 500
#define BLE_RETRY_DELAY_MS 1000

#endif
