#ifndef PROTOCOL_CONFIG_H
#define PROTOCOL_CONFIG_H

#define RAYZ_PROTOCOL_VERSION "1.0.0"

#define BIT_DURATION_MS 150
#define SAMPLE_INTERVAL_MS 10
#define SAMPLES_PER_BIT 15
#define TRANSMISSION_PAUSE_MS 1000
#define COMMUNICATION_TIMEOUT_MS 5000

#define MESSAGE_TOTAL_BITS 16
#define MESSAGE_DATA_BITS 8
#define MESSAGE_HASH_BITS 8

#define PHOTODIODE_BUFFER_SIZE 16
#define MAX_MESSAGE_SIZE 256

#define HASH_XOR_SEED 0b10101010
#define HASH_OFFSET 1

#endif
